// Copyright 2019-2026 pafuhana1213. All Rights Reserved.

#pragma once

#include "CoreMinimal.h"
#include "Engine/DeveloperSettings.h"
#include "KawaiiPhysicsDeveloperSettings.generated.h"

class UKawaiiPhysicsWindPresetDataAsset;

/** MCPノードの自動配置方向。Auto は非接続=縦積み、bAutoConnect=横並びの従来挙動 / Automatic placement direction for MCP nodes. Auto keeps legacy behavior: vertical when not connected, horizontal with bAutoConnect. */
UENUM(BlueprintType)
enum class EKawaiiPhysicsMcpNodePlacementDirection : uint8
{
	/** 自動（非接続は縦積み、bAutoConnect は横並びの従来挙動） / Auto (legacy behavior: vertical when not connected, horizontal with bAutoConnect). */
	Auto,
	/** 縦方向へ配置 / Place vertically. */
	Vertical,
	/** 横方向へ配置 / Place horizontally. */
	Horizontal,
};

/**
 * KawaiiPhysics のプロジェクト全体設定 / Project-wide settings for KawaiiPhysics.
 * Project Settings > Plugins > Kawaii Physics に表示される。
 */
UCLASS(config = Engine, defaultconfig, BlueprintType, meta = (DisplayName = "Kawaii Physics"))
class KAWAIIPHYSICS_API UKawaiiPhysicsDeveloperSettings : public UDeveloperSettings
{
	GENERATED_BODY()

public:
	/**
	* シミュレーション全体を固定タイムステップ（FixedDt = 1/TargetFramerate）でサブステップ実行し、
	* フレームレート依存の挙動を解消する。（低fps時はサブステップ数が増え負荷が上がる）。
	* Run the whole simulation with fixed-timestep substepping (FixedDt = 1/TargetFramerate) for true
	* frame-rate independence (CPU cost rises at low fps as substep count grows).
	*/
	UPROPERTY(EditAnywhere, config, Category = "Simulation",
		meta = (DisplayName = "Use Fixed Substepping"))
	bool bUseFixedSubstepping = true;

	/**
	* 1フレームあたりの最大サブステップ数。低fps/ヒッチ時の暴走（spiral of death）を防ぐ上限。
	* これを超える分の時間は破棄される。
	* Maximum substeps per frame. Caps catch-up at low fps / hitches (prevents spiral of death);
	* time beyond this is dropped.
	*/
	UPROPERTY(EditAnywhere, config, Category = "Simulation",
		meta = (DisplayName = "Max Substeps", ClampMin = "1", UIMin = "1", ClampMax = "16",
			EditCondition = "bUseFixedSubstepping"))
	int32 MaxSubsteps = 4;

#if WITH_EDITORONLY_DATA
	/**
	* MCPコメント枠のタイトルに付与するプレフィックス。
	* Prefix prepended to MCP comment frame titles.
	*/
	UPROPERTY(EditAnywhere, config, Category = "Editor Scripting",
		meta = (DisplayName = "MCP Comment Prefix"))
	FString McpCommentPrefix = TEXT("[MCP] ");

	/**
	* MCPコメント枠の色。
	* Color of MCP comment frames.
	*/
	UPROPERTY(EditAnywhere, config, Category = "Editor Scripting",
		meta = (DisplayName = "MCP Comment Color"))
	FLinearColor McpCommentColor = FLinearColor(0.55f, 0.45f, 0.85f);

	/** MCPノードの自動配置方向。Auto は非接続=縦積み、bAutoConnect=横並びの従来挙動 / Automatic placement direction for MCP nodes. Auto keeps legacy behavior: vertical when not connected, horizontal with bAutoConnect. */
	UPROPERTY(EditAnywhere, config, Category = "Editor Scripting",
		meta = (DisplayName = "MCP Node Placement Direction"))
	EKawaiiPhysicsMcpNodePlacementDirection McpNodePlacementDirection =
		EKawaiiPhysicsMcpNodePlacementDirection::Auto;

	/** MCPノード自動配置の折り返し数。0で折り返しなし / Wrap count for MCP node auto placement. Set to 0 to disable. */
	UPROPERTY(EditAnywhere, config, Category = "Editor Scripting",
		meta = (DisplayName = "MCP Node Placement Wrap Count", ClampMin = "0", UIMin = "0", UIMax = "32"))
	int32 McpNodePlacementWrapCount = 0;

	/**
	* MCPノード自動配置の横方向間隔（グラフ座標単位）。重なり回避の誤判定を防ぐため、想定ノード幅400未満には設定できない。
	* Horizontal spacing for MCP node auto placement (graph coordinate units). Cannot be set below the
	* expected node width of 400 to avoid false-positive overlap detection.
	*/
	UPROPERTY(EditAnywhere, config, Category = "Editor Scripting",
		meta = (DisplayName = "MCP Node Placement Spacing X", ClampMin = "400", UIMin = "400", UIMax = "1000"))
	int32 McpNodePlacementSpacingX = 420;

	/**
	* MCPノード自動配置の縦方向間隔（グラフ座標単位）。重なり回避の誤判定を防ぐため、想定ノード高さ260未満には設定できない。
	* Vertical spacing for MCP node auto placement (graph coordinate units). Cannot be set below the
	* expected node height of 260 to avoid false-positive overlap detection.
	*/
	UPROPERTY(EditAnywhere, config, Category = "Editor Scripting",
		meta = (DisplayName = "MCP Node Placement Spacing Y", ClampMin = "260", UIMin = "260", UIMax = "1000"))
	int32 McpNodePlacementSpacingY = 260;

	/**
	* BoneSubdivisionCount で生成される inter-bone dummy bone 数の警告しきい値。0で警告を無効化する。
	* Warning threshold for inter-bone dummy bones generated by BoneSubdivisionCount. Set to 0 to disable.
	*/
	UPROPERTY(EditAnywhere, config, Category = "Performance Warnings",
		meta = (DisplayName = "Inter-Bone Dummy Warning Threshold", ClampMin = "0", UIMin = "0", UIMax = "1000"))
	int32 InterBoneDummyWarningThreshold = 100;

	/**
	* BoneConstraintSubdivisionCount で生成される bridge collision-proxy dummy bone 数の警告しきい値。0で警告を無効化する。
	* Warning threshold for bridge collision-proxy dummy bones generated by BoneConstraintSubdivisionCount. Set to 0 to disable.
	*/
	UPROPERTY(EditAnywhere, config, Category = "Performance Warnings",
		meta = (DisplayName = "Bridge Dummy Warning Threshold", ClampMin = "0", UIMin = "0", UIMax = "1000"))
	int32 BridgeDummyWarningThreshold = 200;

	/**
	* Wind Scope で表示する風プリセット DataAsset。未設定または Presets 空なら組み込み3種を表示、設定時は完全置換。
	* Wind preset DataAsset shown by Wind Scope. Built-in three presets are shown when unset or Presets is empty; a configured asset fully replaces them.
	*/
	UPROPERTY(EditAnywhere, config, Category = "Wind Scope", meta = (DisplayName = "Wind Preset Data Asset"))
	TSoftObjectPtr<UKawaiiPhysicsWindPresetDataAsset> WindScopePresetDataAsset;
#endif

	//~ UDeveloperSettings interface
	virtual FName GetCategoryName() const override { return FName(TEXT("Plugins")); }
	//~ End of UDeveloperSettings interface
};
