// Copyright 2019-2026 pafuhana1213. All Rights Reserved.

#pragma once

#include "CoreMinimal.h"
#include "BoneContainer.h"
#include "BoneControllers/AnimNode_AnimDynamics.h"

#include "KawaiiPhysicsCollisionLimits.generated.h"

/**
 * Enum representing the type of collision limit in KawaiiPhysics.
 */
UENUM()
enum class ECollisionLimitType : uint8
{
	None,
	Spherical,
	Capsule,
	Box,
	Planar,
	TaperedCapsule,
};

/**
 * Enum representing the source type of the collision limit in KawaiiPhysics.
 */
UENUM()
enum class ECollisionSourceType : uint8
{
	/** Use the value set in the AnimNode */
	AnimNode,
	/** Use the value set in the DataAsset */
	DataAsset,
	/** Use the value set in the PhysicsAsset */
	PhysicsAsset,
	/** Auto-generated by mirroring an existing collision via MirrorDataTable */
	Mirror,
};

/**
 * コリジョンLimitの基底構造体。
 * Base structure for defining collision limits in KawaiiPhysics.
 */
USTRUCT()
struct FCollisionLimitBase
{
	GENERATED_BODY()

	/** コリジョンをアタッチするボーン / Bone to attach the sphere to */
	UPROPERTY(EditAnywhere, Category = "Collision Limit Base")
	FBoneReference DrivingBone;

	/** DrivingBoneからの位置オフセット / Offset location from the driving bone */
	UPROPERTY(EditAnywhere, Category = "Collision Limit Base")
	FVector OffsetLocation = FVector::ZeroVector;

	/** DrivingBoneからの回転オフセット / Offset rotation from the driving bone */
	UPROPERTY(EditAnywhere, Category = "Collision Limit Base", meta = (ClampMin = "-360", ClampMax = "360"))
	FRotator OffsetRotation = FRotator::ZeroRotator;

	/** Location of the collision limit */
	UPROPERTY()
	FVector Location = FVector::ZeroVector;

	/** Rotation of the collision limit */
	UPROPERTY()
	FQuat Rotation = FQuat::Identity;

	/** Whether the collision limit is enabled */
	UPROPERTY()
	bool bEnable = true;

	/** このコリジョンの定義元 / Source type of the collision limit */
	UPROPERTY(VisibleAnywhere, Category = "Collision Limit Base")
	ECollisionSourceType SourceType = ECollisionSourceType::AnimNode;

#if WITH_EDITORONLY_DATA

	/** コリジョンの一意な識別子（エディタ専用） / Unique identifier for the collision limit (editor only) */
	UPROPERTY(VisibleAnywhere, Category = "Debug", meta = (IgnoreForMemberInitializationTest))
	FGuid Guid = FGuid::NewGuid();

	/** Type of the collision limit (editor only) */
	UPROPERTY()
	ECollisionLimitType Type = ECollisionLimitType::None;

#endif

	/** Assignment operator */
	FCollisionLimitBase& operator=(const FCollisionLimitBase& Other)
	{
		DrivingBone = Other.DrivingBone;
		OffsetLocation = Other.OffsetLocation;
		OffsetRotation = Other.OffsetRotation;
		Location = Other.Location;
		Rotation = Other.Rotation;
		bEnable = Other.bEnable;
		SourceType = Other.SourceType;
#if WITH_EDITORONLY_DATA
		Guid = Other.Guid;
		Type = Other.Type;
#endif
		return *this;
	}
};

/**
 * 球のコリジョンLimitを表す構造体。
 * Structure representing a spherical limit for collision in KawaiiPhysics.
 */
USTRUCT(BlueprintType)
struct FSphericalLimit : public FCollisionLimitBase
{
	GENERATED_BODY()

	/** Default constructor */
	FSphericalLimit()
	{
#if WITH_EDITORONLY_DATA
		// Set the collision limit type to spherical
		Type = ECollisionLimitType::Spherical;
#endif
	}

	/** 球の半径 / Radius of the sphere */
	UPROPERTY(EditAnywhere, Category = "Spherical Limit", meta = (ClampMin = "0"))
	float Radius = 5.0f;

	/** 球の外側と内側のどちらに拘束するか / Whether to lock bodies inside or outside of the sphere */
	UPROPERTY(EditAnywhere, Category = "Spherical Limit")
	ESphericalLimitType LimitType = ESphericalLimitType::Outer;

	/** Assignment operator */
	FSphericalLimit& operator=(const FSphericalLimit& Other)
	{
		FCollisionLimitBase::operator=(Other);
		Radius = Other.Radius;
		LimitType = Other.LimitType;
		return *this;
	}
};

/**
 * カプセルのコリジョンLimitを表す構造体。
 * Structure representing a capsule limit for collision in KawaiiPhysics.
 */
USTRUCT(BlueprintType)
struct FCapsuleLimit : public FCollisionLimitBase
{
	GENERATED_BODY()

	/** Default constructor */
	FCapsuleLimit()
	{
#if WITH_EDITORONLY_DATA
		// Set the collision limit type to capsule
		Type = ECollisionLimitType::Capsule;
#endif
	}

	/** カプセルの半径 / Radius of the capsule */
	UPROPERTY(EditAnywhere, Category = "Capsule Limit", meta = (ClampMin = "0"))
	float Radius = 5.0f;

	/** カプセルの長さ / Length of the capsule */
	UPROPERTY(EditAnywhere, Category = "Capsule Limit", meta = (ClampMin = "0"))
	float Length = 10.0f;

	/** Assignment operator */
	FCapsuleLimit& operator=(const FCapsuleLimit& Other)
	{
		FCollisionLimitBase::operator=(Other);
		Radius = Other.Radius;
		Length = Other.Length;
		return *this;
	}
};

/**
 * テーパードカプセルのコリジョンLimitを表す構造体。
 * Structure representing a tapered capsule limit for collision in KawaiiPhysics.
 */
USTRUCT(BlueprintType)
struct FTaperedCapsuleLimit : public FCollisionLimitBase
{
	GENERATED_BODY()

	/** Default constructor */
	FTaperedCapsuleLimit()
	{
#if WITH_EDITORONLY_DATA
		// Set the collision limit type to tapered capsule
		Type = ECollisionLimitType::TaperedCapsule;
#endif
	}

	/** +Z端の半径 / Radius at the +Z end */
	UPROPERTY(EditAnywhere, Category = "Tapered Capsule Limit", meta = (ClampMin = "0"))
	float Radius0 = 5.0f;

	/** -Z端の半径 / Radius at the -Z end */
	UPROPERTY(EditAnywhere, Category = "Tapered Capsule Limit", meta = (ClampMin = "0"))
	float Radius1 = 5.0f;

	/** カプセルの長さ / Length of the capsule */
	UPROPERTY(EditAnywhere, Category = "Tapered Capsule Limit", meta = (ClampMin = "0"))
	float Length = 10.0f;

	/** Assignment operator */
	FTaperedCapsuleLimit& operator=(const FTaperedCapsuleLimit& Other)
	{
		FCollisionLimitBase::operator=(Other);
		Radius0 = Other.Radius0;
		Radius1 = Other.Radius1;
		Length = Other.Length;
		return *this;
	}
};

/**
 * ボックスのコリジョンLimitを表す構造体。
 * Structure representing a box limit for collision in KawaiiPhysics.
 */
USTRUCT(BlueprintType)
struct FBoxLimit : public FCollisionLimitBase
{
	GENERATED_BODY()

	/** Default constructor */
	FBoxLimit()
	{
#if WITH_EDITORONLY_DATA
		// Set the collision limit type to box
		Type = ECollisionLimitType::Box;
#endif
	}

	/** ボックスの各軸方向のサイズ（半分の大きさ） / The extent of the box defining the box limit */
	UPROPERTY(EditAnywhere, Category = "Box Limit")
	FVector Extent = FVector(5.0f, 5.0f, 5.0f);

	/** Assignment operator */
	FBoxLimit& operator=(const FBoxLimit& Other)
	{
		FCollisionLimitBase::operator=(Other);
		Extent = Other.Extent;
		return *this;
	}
};

/**
 * 平面のコリジョンLimitを表す構造体。
 * Structure representing a planar limit for collision in KawaiiPhysics.
 */
USTRUCT(BlueprintType)
struct FPlanarLimit : public FCollisionLimitBase
{
	GENERATED_BODY()

	/** Default constructor */
	FPlanarLimit()
	{
#if WITH_EDITORONLY_DATA
		// Set the collision limit type to planar
		Type = ECollisionLimitType::Planar;
#endif
	}

	/** The plane defining the planar limit */
	UPROPERTY()
	FPlane Plane = FPlane(0, 0, 0, 0);

	/** Assignment operator */
	FPlanarLimit& operator=(const FPlanarLimit& Other)
	{
		FCollisionLimitBase::operator=(Other);
		Plane = Other.Plane;
		return *this;
	}
};
