// Copyright 2019-2026 pafuhana1213. All Rights Reserved.

#pragma once

#include "CoreMinimal.h"
#include "Engine/DeveloperSettings.h"
#include "KawaiiPhysicsDeveloperSettings.generated.h"

/**
 * KawaiiPhysics のプロジェクト全体設定 / Project-wide settings for KawaiiPhysics.
 * Project Settings > Plugins > Kawaii Physics に表示される。
 */
UCLASS(config = Engine, defaultconfig, BlueprintType, meta = (DisplayName = "Kawaii Physics"))
class KAWAIIPHYSICS_API UKawaiiPhysicsDeveloperSettings : public UDeveloperSettings
{
	GENERATED_BODY()

public:
	/**
	* シミュレーション全体を固定タイムステップ（FixedDt = 1/TargetFramerate）でサブステップ実行し、
	* フレームレート依存の挙動を解消する。（低fps時はサブステップ数が増え負荷が上がる）。
	* Run the whole simulation with fixed-timestep substepping (FixedDt = 1/TargetFramerate) for true
	* frame-rate independence (CPU cost rises at low fps as substep count grows).
	*/
	UPROPERTY(EditAnywhere, config, Category = "Simulation",
		meta = (DisplayName = "Use Fixed Substepping"))
	bool bUseFixedSubstepping = true;

	/**
	* 1フレームあたりの最大サブステップ数。低fps/ヒッチ時の暴走（spiral of death）を防ぐ上限。
	* これを超える分の時間は破棄される。
	* Maximum substeps per frame. Caps catch-up at low fps / hitches (prevents spiral of death);
	* time beyond this is dropped.
	*/
	UPROPERTY(EditAnywhere, config, Category = "Simulation",
		meta = (DisplayName = "Max Substeps", ClampMin = "1", UIMin = "1", ClampMax = "16",
			EditCondition = "bUseFixedSubstepping"))
	int32 MaxSubsteps = 4;

#if WITH_EDITORONLY_DATA
	/**
	* MCPコメント枠のタイトルに付与するプレフィックス。
	* Prefix prepended to MCP comment frame titles.
	*/
	UPROPERTY(EditAnywhere, config, Category = "Editor Scripting",
		meta = (DisplayName = "MCP Comment Prefix"))
	FString McpCommentPrefix = TEXT("[MCP] ");

	/**
	* MCPコメント枠の色。
	* Color of MCP comment frames.
	*/
	UPROPERTY(EditAnywhere, config, Category = "Editor Scripting",
		meta = (DisplayName = "MCP Comment Color"))
	FLinearColor McpCommentColor = FLinearColor(0.55f, 0.45f, 0.85f);

	/**
	* BoneSubdivisionCount で生成される inter-bone dummy bone 数の警告しきい値。0で警告を無効化する。
	* Warning threshold for inter-bone dummy bones generated by BoneSubdivisionCount. Set to 0 to disable.
	*/
	UPROPERTY(EditAnywhere, config, Category = "Performance Warnings",
		meta = (DisplayName = "Inter-Bone Dummy Warning Threshold", ClampMin = "0", UIMin = "0", UIMax = "1000"))
	int32 InterBoneDummyWarningThreshold = 100;

	/**
	* BoneConstraintSubdivisionCount で生成される bridge collision-proxy dummy bone 数の警告しきい値。0で警告を無効化する。
	* Warning threshold for bridge collision-proxy dummy bones generated by BoneConstraintSubdivisionCount. Set to 0 to disable.
	*/
	UPROPERTY(EditAnywhere, config, Category = "Performance Warnings",
		meta = (DisplayName = "Bridge Dummy Warning Threshold", ClampMin = "0", UIMin = "0", UIMax = "1000"))
	int32 BridgeDummyWarningThreshold = 200;
#endif

	//~ UDeveloperSettings interface
	virtual FName GetCategoryName() const override { return FName(TEXT("Plugins")); }
	//~ End of UDeveloperSettings interface
};
