// Copyright 2019-2026 pafuhana1213. All Rights Reserved.

#pragma once

#include "KawaiiPhysicsBoneConstraintTypes.h"
#include "Engine/DataAsset.h"
#include "Interfaces/Interface_BoneReferenceSkeletonProvider.h"
#include "KawaiiPhysicsBoneConstraintsDataAsset.generated.h"

UENUM()
enum class EBoneConstraintSourceType : uint8
{
	Manual,    // 手動追加 / Manually added
	Regex,     // ApplyRegexで生成 / Generated by ApplyRegex
	ChainGen,  // ApplyChainsで生成 / Generated by ApplyChains
};

UENUM()
enum class EBoneChainRatioMode : uint8
{
	// チェーン内インデックス比で対応付け / Match by chain index ratio
	IndexRatio,

	// 参照ポーズのボーン長累積比で対応付け / Match by cumulative reference-pose bone length ratio
	LengthRatio,
};

/**
 * Struct representing the data for modifying bone constraints in KawaiiPhysics.
 */
USTRUCT(BlueprintType)
struct KAWAIIPHYSICS_API FModifyBoneConstraintData
{
	GENERATED_BODY()

	/** Name of the first bone (deprecated) */
	UPROPERTY()
	FName BoneName1;

	/** Name of the second bone (deprecated) */
	UPROPERTY()
	FName BoneName2;

	/** Reference to the first bone */
	UPROPERTY(EditAnywhere, category = "KawaiiPhysics")
	FBoneReference BoneReference1;

	/** Reference to the second bone */
	UPROPERTY(EditAnywhere, category = "KawaiiPhysics")
	FBoneReference BoneReference2;

	/** Whether to override the compliance type */
	UPROPERTY(EditAnywhere, category = "KawaiiPhysics", meta=(InlineEditConditionToggle))
	bool bOverrideCompliance = false;

	/** The compliance type to use if overriding */
	UPROPERTY(EditAnywhere, category = "KawaiiPhysics", meta=(EditCondition="bOverrideCompliance"))
	EXPBDComplianceType ComplianceType = EXPBDComplianceType::Leather;

	/**
	 * このConstraintをBoneConstraintSubdivisionの対象から除外する（構造/対角Constraint用のオプトアウト）
	 * Exclude this constraint from BoneConstraintSubdivision (opt-out for structural/diagonal constraints).
	 */
	UPROPERTY(EditAnywhere, category = "KawaiiPhysics")
	bool bExcludeFromSubdivision = false;

#if WITH_EDITORONLY_DATA
	/**
	 * このペアの生成元（ApplyChains再実行時のマージ対象の識別。Manualにすると自動再生成の対象外）
	 * Source of this pair (identifies merge targets on ApplyChains re-run; set to Manual to opt out of regeneration)
	 */
	UPROPERTY(EditAnywhere, Category = "KawaiiPhysics")
	EBoneConstraintSourceType SourceType = EBoneConstraintSourceType::Manual;
#endif

	/**
	 * Updates the bone constraint data with the given constraint.
	 * @param BoneConstraint The bone constraint to update from.
	 */
	void Update(const FModifyBoneConstraint& BoneConstraint);
};

/**
 * Struct representing a set of regex patterns for bones in KawaiiPhysics.
 */
USTRUCT(BlueprintType)
struct FRegexPatternBoneSet
{
	GENERATED_BODY()

	/** Regex pattern for the first bone */
	UPROPERTY(EditAnywhere, Category="Helper")
	FString RegexPatternBone1;

	/** Regex pattern for the second bone */
	UPROPERTY(EditAnywhere, Category="Helper")
	FString RegexPatternBone2;
};

USTRUCT()
struct FKawaiiPhysicsBoneChainGroup
{
	GENERATED_BODY()

	// グループ名（表示・通知用）/ Group label (for display and notifications)
	UPROPERTY(EditAnywhere, Category = "Chain Generator")
	FString GroupName;

	// 各チェーンのルートボーンを隣接順に指定 / Root bone of each chain in adjacency order
	UPROPERTY(EditAnywhere, Category = "Chain Generator")
	TArray<FBoneReference> ChainRootBones;

	// 横方向の接続数。0=ループ（全隣接＋末尾↔先頭を接続、スカート等）、1以上=配列先頭からその数の隣接接続のみ生成（前面だけ等の部分接続）
	// Lateral connection count. 0 = loop (all adjacencies + last-to-first, e.g. skirts); >=1 = generate only that many adjacent connections from the head of the array (partial connection such as front-only)
	UPROPERTY(EditAnywhere, Category = "Chain Generator", meta = (ClampMin = "0", UIMin = "0"))
	int32 LateralConnectionCount = 0;

	// DetectChains用の検索ルート（設定時のみ検出対象）/ Search root for DetectChains (detected only when set)
	UPROPERTY(EditAnywhere, Category = "Chain Generator")
	FBoneReference DetectRootBone;

	// 生成ペアのCompliance上書き / Compliance override for generated pairs
	UPROPERTY(EditAnywhere, Category = "Chain Generator", meta = (InlineEditConditionToggle))
	bool bOverrideCompliance = false;

	UPROPERTY(EditAnywhere, Category = "Chain Generator", meta = (EditCondition = "bOverrideCompliance"))
	EXPBDComplianceType ComplianceType = EXPBDComplianceType::Leather;

	// 生成ペアをSubdivision対象から除外 / Exclude generated pairs from subdivision
	UPROPERTY(EditAnywhere, Category = "Chain Generator")
	bool bExcludeFromSubdivision = false;
};


/**
 * Data asset for managing bone constraints in KawaiiPhysics.
 */
UCLASS(Blueprintable)
class KAWAIIPHYSICS_API UKawaiiPhysicsBoneConstraintsDataAsset : public UDataAsset,
                                                                 public IBoneReferenceSkeletonProvider
{
	GENERATED_BODY()

public:
	/** Array of bone constraint data */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Bone Constraint (Experimental)",
		meta=(TitleProperty="{BoneReference1} - {BoneReference2}"))
	TArray<FModifyBoneConstraintData> BoneConstraintsData;

#if WITH_EDITORONLY_DATA

	/** List of regex patterns for bones */
	UPROPERTY(EditAnywhere, Category="Helper")
	TArray<FRegexPatternBoneSet> RegexPatternList;

	/**
	 * チェーングループ（スカート/髪/マント等、部位ごとに1グループ）
	 * Chain groups (one per part: skirt / hair / cape, etc.)
	 */
	UPROPERTY(EditAnywhere, Category = "Chain Generator", meta = (TitleProperty = "{GroupName}"))
	TArray<FKawaiiPhysicsBoneChainGroup> ChainGroups;

	/**
	 * チェーン内相対位置の算出方法（インデックス比/ボーン長累積比）
	 * How to compute relative position within a chain (index ratio / cumulative length ratio)
	 */
	UPROPERTY(EditAnywhere, Category = "Chain Generator|Advanced")
	EBoneChainRatioMode ChainRatioMode = EBoneChainRatioMode::IndexRatio;

	/** Preview skeleton for editor */
	UPROPERTY(EditAnywhere, Category = "Skeleton")
	TSoftObjectPtr<USkeleton> PreviewSkeleton;

	/** List of preview bones */
	UPROPERTY(VisibleAnywhere, Category = "Skeleton", meta= (EditCondition=false))
	TArray<FBoneReference> PreviewBoneList;

	/** String representation of the preview bone list */
	UPROPERTY()
	FString PreviewBoneListString;
#endif

	// Begin UObject Interface.
	virtual void Serialize(FStructuredArchiveRecord Record) override;
	virtual void PostLoad() override;
	// End UObject Interface.

	// IBoneReferenceSkeletonProvider interface
	virtual USkeleton* GetSkeleton(bool& bInvalidSkeletonIsError, const IPropertyHandle* PropertyHandle) override;

	/** Generates bone constraints based on the current data */
	TArray<FModifyBoneConstraint> GenerateBoneConstraints();

#if WITH_EDITOR

	/** Applies regex patterns to the bone constraints */
	UFUNCTION(BlueprintCallable, CallInEditor, Category="Helper")
	void ApplyRegex();

	/**
	 * チェーングループからBoneConstraintsDataへ拘束ペアを生成・マージする
	 * Generates and merges constraint pairs from chain groups into BoneConstraintsData.
	 */
	UFUNCTION(BlueprintCallable, CallInEditor, Category = "Chain Generator")
	void ApplyChains();

	/**
	 * DetectRootBoneが設定されたチェーングループのChainRootBonesを自動検出・充填する
	 * Detects and fills ChainRootBones for chain groups that have DetectRootBone set.
	 */
	UFUNCTION(BlueprintCallable, CallInEditor, Category = "Chain Generator")
	void DetectChains();

	/** Updates the preview bone list */
	void UpdatePreviewBoneList();

	/** Handles property changes in the editor */
	virtual void PostEditChangeProperty(struct FPropertyChangedEvent& PropertyChangedEvent) override;
#endif
};
